"""Tests for AI contamination detection (ALLIE-433).

Covers:
- Heuristic scoring of known AI patterns (high score)
- Heuristic scoring of known human patterns (low score)
- Middle-zone items trigger LLM path
- classify_evidence_contamination sync wrapper
- browse_evidence / search_evidence respecting exclude_contaminated flag
"""

from __future__ import annotations

import json
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from app.ingestion.ai_contamination import (
    AI_STOCK_PHRASES,
    STOCK_PHRASE_COUNT,
    _HEURISTIC_CONFIDENT_HIGH,
    _HEURISTIC_CONFIDENT_LOW,
    classify_evidence_contamination,
    score_ai_contamination,
    score_heuristic,
)


# ── Heuristic scorer ─────────────────────────────────────────────────────────


class TestScoreHeuristic:
    """Unit tests for the fast heuristic scorer."""

    def test_empty_text_returns_zero(self):
        assert score_heuristic("") == 0.0

    def test_none_like_short_text_returns_zero(self):
        assert score_heuristic("ok") == 0.0

    def test_ai_opener_happy_to_help(self):
        score = score_heuristic("I'd be happy to help you with that!")
        # "happy to help" phrase alone clears the low threshold
        assert score > _HEURISTIC_CONFIDENT_LOW

    def test_ai_opener_certainly(self):
        score = score_heuristic("Certainly, let me explain the architecture for you.")
        assert score >= _HEURISTIC_CONFIDENT_LOW

    def test_ai_opener_sure_heres(self):
        score = score_heuristic("Sure, here's how you can fix this bug.")
        assert score >= _HEURISTIC_CONFIDENT_LOW

    def test_ai_phrase_great_question(self):
        score = score_heuristic("Great question! Let me break this down for you.")
        # Two AI patterns; must exceed the low threshold
        assert score > _HEURISTIC_CONFIDENT_LOW

    def test_ai_phrase_lets_break_down(self):
        score = score_heuristic("Let's break this down into manageable steps.")
        assert score >= _HEURISTIC_CONFIDENT_LOW

    def test_ai_phrase_in_summary(self):
        score = score_heuristic("In summary, the approach reduces complexity significantly.")
        assert score >= _HEURISTIC_CONFIDENT_LOW

    def test_ai_phrase_hope_this_helps(self):
        score = score_heuristic(
            "This should resolve the issue. Hope this helps! Let me know if you have questions."
        )
        assert score >= _HEURISTIC_CONFIDENT_LOW

    def test_as_an_ai_phrase(self):
        score = score_heuristic("As an AI language model, I don't have opinions on frameworks.")
        # "as an AI language model" is a strong AI signal (0.50 increment)
        assert score >= 0.5

    def test_copilot_attribution(self):
        score = score_heuristic("This PR description was AI generated by GitHub Copilot.")
        # Copilot attribution pattern adds 0.60; must exceed low threshold
        assert score > _HEURISTIC_CONFIDENT_LOW

    def test_heavy_enumeration_boosts_score(self):
        text = (
            "Here are the main points:\n"
            "1. First we need to set up the environment.\n"
            "2. Then configure the database connection.\n"
            "3. Finally run the migrations.\n"
            "4. Verify everything works correctly.\n"
        )
        score = score_heuristic(text)
        assert score >= _HEURISTIC_CONFIDENT_LOW

    def test_human_terse_pr_comment_is_low(self):
        score = score_heuristic("nit: this should use `is None` instead of `== None`")
        assert score < _HEURISTIC_CONFIDENT_LOW

    def test_human_blunt_review_is_low(self):
        score = score_heuristic(
            "This is wrong. We never store secrets in env vars checked into git."
        )
        assert score < _HEURISTIC_CONFIDENT_LOW

    def test_human_typo_commit_message_is_low(self):
        score = score_heuristic("fixd the nul pointer exceptoin in auth middleware lol")
        assert score < _HEURISTIC_CONFIDENT_LOW

    def test_human_informal_comment_is_low(self):
        score = score_heuristic("yeah this is fine, ship it. we can clean up the abstraction later")
        assert score < _HEURISTIC_CONFIDENT_LOW

    def test_score_clamped_to_one(self):
        # Pile on many AI phrases — must not exceed 1.0
        text = (
            "I'd be happy to help! Certainly, of course. "
            "Great question! Sure, here's the answer. "
            "As an AI language model, let's break this down. "
            "In summary: hope this helps. Feel free to ask. "
            "Don't hesitate to reach out. This PR introduces a new feature. "
            "Best regards."
        )
        assert score_heuristic(text) == 1.0

    def test_stock_phrase_count(self):
        """Sanity-check that the pattern list is non-trivial."""
        assert STOCK_PHRASE_COUNT >= 20

    def test_all_patterns_compile(self):
        """All patterns in AI_STOCK_PHRASES are valid compiled regexes."""
        for name, pattern, increment in AI_STOCK_PHRASES:
            assert hasattr(pattern, "search"), f"Pattern {name} is not compiled"
            assert 0.0 < increment <= 1.0, f"Increment for {name} out of range"


# ── score_ai_contamination (async) ───────────────────────────────────────────


class TestScoreAiContamination:
    """Integration-level tests for the async scorer."""

    @pytest.mark.asyncio
    async def test_clearly_human_skips_llm(self):
        """Heuristic-confident human text must not hit the LLM."""
        with patch(
            "app.ingestion.ai_contamination._score_via_llm",
            new_callable=AsyncMock,
        ) as mock_llm:
            score = await score_ai_contamination(
                "nit: rename the variable to `session_id` for clarity"
            )
        mock_llm.assert_not_called()
        assert score < _HEURISTIC_CONFIDENT_LOW

    @pytest.mark.asyncio
    async def test_clearly_ai_skips_llm(self):
        """Heuristic-confident AI text must not hit the LLM."""
        with patch(
            "app.ingestion.ai_contamination._score_via_llm",
            new_callable=AsyncMock,
        ) as mock_llm:
            score = await score_ai_contamination(
                "I'd be happy to help! Great question! As an AI language model, "
                "certainly, let's break this down. In summary: hope this helps!"
            )
        mock_llm.assert_not_called()
        assert score > _HEURISTIC_CONFIDENT_HIGH

    @pytest.mark.asyncio
    async def test_middle_zone_triggers_llm(self):
        """Ambiguous text in the 0.2–0.8 band must call the LLM."""
        # Craft text with a single borderline phrase that lands in middle zone
        # "hope this helps" → 0.25 heuristic; reliably in middle zone
        borderline = "Hope this helps with your project. Let me know if there are issues."

        h = score_heuristic(borderline)
        assert _HEURISTIC_CONFIDENT_LOW <= h <= _HEURISTIC_CONFIDENT_HIGH, (
            f"Test invariant broken: heuristic score {h} not in middle zone"
        )

        with patch(
            "app.ingestion.ai_contamination._score_via_llm",
            new_callable=AsyncMock,
            return_value=0.6,
        ) as mock_llm:
            score = await score_ai_contamination(borderline)

        mock_llm.assert_called_once()
        assert 0.0 <= score <= 1.0

    @pytest.mark.asyncio
    async def test_returns_zero_for_short_text(self):
        score = await score_ai_contamination("hi")
        assert score == 0.0

    @pytest.mark.asyncio
    async def test_llm_failure_returns_blended_not_crash(self):
        """If LLM raises in middle zone, _score_via_llm catches it and returns 0.5."""
        borderline = "Hope this helps with your project. Let me know if there are issues."

        h = score_heuristic(borderline)
        assert _HEURISTIC_CONFIDENT_LOW <= h <= _HEURISTIC_CONFIDENT_HIGH, (
            f"Test invariant broken: heuristic score {h} not in middle zone"
        )

        # _score_via_llm catches all exceptions internally and returns 0.5.
        # We verify that by patching it to return the fallback value directly,
        # confirming score_ai_contamination blends it without crashing.
        with patch(
            "app.ingestion.ai_contamination._score_via_llm",
            new_callable=AsyncMock,
            return_value=0.5,  # fallback value _score_via_llm returns on failure
        ):
            score = await score_ai_contamination(borderline)

        assert 0.0 <= score <= 1.0


# ── classify_evidence_contamination (sync wrapper) ───────────────────────────


class TestClassifyEvidenceContamination:
    def test_returns_score_when_present(self):
        ev = MagicMock()
        ev.ai_contamination_score = 0.75
        assert classify_evidence_contamination(ev) == 0.75

    def test_returns_zero_when_score_none(self):
        ev = MagicMock()
        ev.ai_contamination_score = None
        assert classify_evidence_contamination(ev) == 0.0

    def test_returns_zero_when_attribute_missing(self):
        class FakeEvidence:
            pass

        assert classify_evidence_contamination(FakeEvidence()) == 0.0

    def test_coerces_to_float(self):
        ev = MagicMock()
        ev.ai_contamination_score = 0  # int zero
        assert isinstance(classify_evidence_contamination(ev), float)


# ── browse_evidence / search_evidence contamination filter ───────────────────


class TestExplorerToolsContamination:
    """Test that explorer tools respect the exclude_contaminated flag."""

    @pytest.fixture
    def make_evidence_row(self):
        """Factory for mock Evidence rows."""

        def _make(score: float | None, item_id: str = "ev-1", content: str = "some content"):
            row = MagicMock()
            row.id = item_id
            row.mini_id = "mini-1"
            row.source_type = "github"
            row.item_type = "pr"
            row.content = content
            row.explored = False
            row.source_privacy = "public"
            row.created_at = None
            row.ai_contamination_score = score
            return row

        return _make

    @pytest.mark.asyncio
    async def test_browse_excludes_high_contamination_by_default(self, make_evidence_row):
        """browse_evidence with default exclude_contaminated=True must apply WHERE filter."""
        from app.synthesis.explorers.tools import build_explorer_tools

        db_session = AsyncMock()

        # Simulate two DB results: count query returns 1, items query returns 1 clean row
        clean_row = make_evidence_row(score=0.1, item_id="clean")
        count_result = MagicMock()
        count_result.scalar.return_value = 1
        items_result = MagicMock()
        items_result.scalars.return_value.all.return_value = [clean_row]

        db_session.execute = AsyncMock(side_effect=[items_result, count_result])

        tools = build_explorer_tools(
            mini_id="mini-1",
            source_type="github",
            db_session=db_session,
        )
        browse = next(t for t in tools if t.name == "browse_evidence")
        response = await browse.handler(source_type="github")
        data = json.loads(response)

        assert data["exclude_contaminated"] is True
        assert data["total"] == 1

    @pytest.mark.asyncio
    async def test_browse_includes_all_when_flag_false(self, make_evidence_row):
        """browse_evidence with exclude_contaminated=False must not apply contamination filter."""
        from app.synthesis.explorers.tools import build_explorer_tools

        db_session = AsyncMock()

        all_rows = [
            make_evidence_row(score=0.9, item_id="ai-1"),
            make_evidence_row(score=0.1, item_id="human-1"),
        ]
        items_result = MagicMock()
        items_result.scalars.return_value.all.return_value = all_rows
        count_result = MagicMock()
        count_result.scalar.return_value = 2

        db_session.execute = AsyncMock(side_effect=[items_result, count_result])

        tools = build_explorer_tools(
            mini_id="mini-1",
            source_type="github",
            db_session=db_session,
        )
        browse = next(t for t in tools if t.name == "browse_evidence")
        response = await browse.handler(source_type="github", exclude_contaminated=False)
        data = json.loads(response)

        assert data["exclude_contaminated"] is False

    @pytest.mark.asyncio
    async def test_search_excludes_contaminated_by_default(self, make_evidence_row):
        """search_evidence must include exclude_contaminated=True in response by default."""
        from app.synthesis.explorers.tools import build_explorer_tools

        db_session = AsyncMock()
        clean_row = make_evidence_row(score=0.0, item_id="clean", content="merge the PR now")
        result = MagicMock()
        result.scalars.return_value.all.return_value = [clean_row]
        db_session.execute = AsyncMock(return_value=result)

        tools = build_explorer_tools(
            mini_id="mini-1",
            source_type="github",
            db_session=db_session,
        )
        search = next(t for t in tools if t.name == "search_evidence")
        response = await search.handler(query="merge")
        data = json.loads(response)

        assert data["exclude_contaminated"] is True

    @pytest.mark.asyncio
    async def test_save_quote_rejects_high_contamination_evidence(self, make_evidence_row):
        """save_quote must return rejected=True when evidence_id points to AI content."""
        from app.synthesis.explorers.tools import build_explorer_tools

        db_session = AsyncMock()
        ai_row = make_evidence_row(score=0.9, item_id="ai-ev-1")
        ev_result = MagicMock()
        ev_result.scalar_one_or_none.return_value = ai_row
        db_session.execute = AsyncMock(return_value=ev_result)

        tools = build_explorer_tools(
            mini_id="mini-1",
            source_type="github",
            db_session=db_session,
        )
        save_quote = next(t for t in tools if t.name == "save_quote")
        response = await save_quote.handler(
            quote="I'd be happy to help!",
            context="PR description",
            significance="communication style",
            evidence_id="ai-ev-1",
        )
        data = json.loads(response)

        assert data["saved"] is False
        assert data["rejected"] is True
        assert "contamination" in data["reason"].lower()

    @pytest.mark.asyncio
    async def test_save_quote_accepts_clean_evidence(self, make_evidence_row):
        """save_quote must save when evidence_id points to clean (human) content."""
        from app.synthesis.explorers.tools import build_explorer_tools

        write_session = AsyncMock()
        write_session.__aenter__ = AsyncMock(return_value=write_session)
        write_session.__aexit__ = AsyncMock(return_value=False)
        write_session.add = MagicMock()
        write_session.commit = AsyncMock()

        # session_factory() must be synchronous (returns an async context manager)
        session_factory = MagicMock(return_value=write_session)

        db_session = AsyncMock()
        clean_row = make_evidence_row(score=0.1, item_id="clean-ev-1")
        ev_result = MagicMock()
        ev_result.scalar_one_or_none.return_value = clean_row
        progress_result = MagicMock()
        db_session.execute = AsyncMock(side_effect=[ev_result, progress_result])

        tools = build_explorer_tools(
            mini_id="mini-1",
            source_type="github",
            db_session=db_session,
            session_factory=session_factory,
        )
        save_quote = next(t for t in tools if t.name == "save_quote")
        response = await save_quote.handler(
            quote="this is wrong, revert it",
            context="code review",
            significance="directness",
            evidence_id="clean-ev-1",
        )
        data = json.loads(response)

        assert data["saved"] is True
        assert data.get("rejected") is not True

    @pytest.mark.asyncio
    async def test_save_quote_without_evidence_id_always_saves(self):
        """save_quote without evidence_id must never apply contamination check."""
        from app.synthesis.explorers.tools import build_explorer_tools

        write_session = AsyncMock()
        write_session.__aenter__ = AsyncMock(return_value=write_session)
        write_session.__aexit__ = AsyncMock(return_value=False)
        write_session.add = MagicMock()
        write_session.commit = AsyncMock()

        # session_factory() must be synchronous
        session_factory = MagicMock(return_value=write_session)

        db_session = AsyncMock()
        progress_result = MagicMock()
        db_session.execute = AsyncMock(return_value=progress_result)

        tools = build_explorer_tools(
            mini_id="mini-1",
            source_type="github",
            db_session=db_session,
            session_factory=session_factory,
        )
        save_quote = next(t for t in tools if t.name == "save_quote")
        response = await save_quote.handler(
            quote="ship it",
            context="PR review",
            significance="decisive",
        )
        data = json.loads(response)

        assert data["saved"] is True
