"""add cascade delete to ingestion_data foreign keys

Revision ID: 23384e5bf831
Revises: 397e6051c9ce
Create Date: 2026-02-12 09:25:41.475325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23384e5bf831'
down_revision: Union[str, None] = '397e6051c9ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ingestion_data_mini_id_fkey'), 'ingestion_data', type_='foreignkey')
    op.create_foreign_key(None, 'ingestion_data', 'minis', ['mini_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('mini_repo_config_mini_id_fkey'), 'mini_repo_config', type_='foreignkey')
    op.create_foreign_key(None, 'mini_repo_config', 'minis', ['mini_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mini_repo_config', type_='foreignkey')
    op.create_foreign_key(op.f('mini_repo_config_mini_id_fkey'), 'mini_repo_config', 'minis', ['mini_id'], ['id'])
    op.drop_constraint(None, 'ingestion_data', type_='foreignkey')
    op.create_foreign_key(op.f('ingestion_data_mini_id_fkey'), 'ingestion_data', 'minis', ['mini_id'], ['id'])
    # ### end Alembic commands ###
